In [1]:
import pandas as pd
import glob as glob

In [2]:
meta_data = pd.read_csv('/data2st1/junyi/methlyatlas/mCseq/CEMBA.mC.Metadata/CEMBA.mC.Metadata.csv')

In [4]:
meta_sample = pd.read_csv('/home/junyichen/code/scmmd/data/TotalGEOMetadata.2021+2023.csv')

/tmp/ipykernel_3706463/3107635359.py:1: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  meta_sample = pd.read_csv('/home/junyichen/code/scmmd/data/TotalGEOMetadata.2021+2023.csv')

In [5]:
meta_annotated = pd.read_csv('/home/junyichen/code/scmmd/output/merged-all-pfc-annotated.csv',index_col=0)

/tmp/ipykernel_3706463/3115723909.py:1: DtypeWarning: Columns (1,2,17,18,19,20,21,22,23,25,26,31,32,36,37,41,42,43,44,45,46,47,56,85) have mixed types. Specify dtype option on import or set low_memory=False.
  meta_annotated = pd.read_csv('/home/junyichen/code/scmmd/output/merged-all-pfc-annotated.csv',index_col=0)

In [5]:
mapping = {
    'Oligo NN': 'OPC-Oligo',
    'Microglia NN': 'Immune',
    'Endo NN': 'Vascular',
    'Astro-TE NN': 'Astro-Epen',
    'Astro-OLF NN': 'Astro-Epen',
    'Astro-NT NN': 'Astro-Epen',
    'Astroependymal NN': 'Astro-Epen',
    'Hypendymal NN': 'Astro-Epen',
    'Ependymal NN': 'Astro-Epen',
    'Tanycyte NN': 'Astro-Epen',
    'Bergmann NN': 'Astro-Epen',
    'CHOR NN': 'Astro-Epen',
    'Astro-CB NN': 'Astro-Epen',
    'OPC NN': 'OPC-Oligo',
    'OEC NN': 'Astro-Epen',
    'BAM NN': 'Immune',
    'DC NN': 'Immune',
    'Lymphoid NN': 'Immune',
    'VLMC NN': 'Vascular',
    'ABC NN': 'Immune',
    'SMC NN': 'Vascular',
    'Peri NN': 'Vascular'
}

In [6]:
set(meta_data['SubClass'])

{'ABC NN',
 'ACB-BST-FS D1 Gaba',
 'AD Serpinb7 Glut',
 'ADP-MPO Trp73 Glut',
 'AHN Onecut3 Gaba',
 'AHN-RCH-LHA Otp Fezf1 Glut',
 'AHN-SBPV-PVHd Pdrm12 Gaba',
 'APN C1ql2 Glut',
 'APN C1ql4 Glut',
 'ARH-PVp Tbx3 Gaba',
 'ARH-PVp Tbx3 Glut',
 'AV Col27a1 Glut',
 'AVPV-MEPO-SFO Tbr1 Glut',
 'Astro-NT NN',
 'Astro-TE NN',
 'B-PB Nr4a2 Glut',
 'BST Tac2 Gaba',
 'BST-MPN Six3 Nrgn Gaba',
 'BST-SI-AAA Six3 Slc22a3 Gaba',
 'BST-po Iigp1 Glut',
 'Bergmann NN',
 'CA1-ProS Glut',
 'CA2-FC-IG Glut',
 'CA3 Glut',
 'CB Granule Glut',
 'CB PLI Gly-Gaba',
 'CBN Neurod2 Pvalb Glut',
 'CBX Golgi Gly-Gaba',
 'CBX MLI Cdh22 Gaba',
 'CBX MLI Megf11 Gaba',
 'CBX Purkinje Gaba',
 'CEA-AAA-BST Six3 Sp9 Gaba',
 'CEA-BST Ebf1 Pdyn Gaba',
 'CEA-BST Gal Avp Gaba',
 'CEA-BST Rai14 Pdyn Crh Gaba',
 'CEA-BST Six3 Cyp26b1 Gaba',
 'CHOR NN',
 'CLA-EPd-CTX Car3 Glut',
 'CM-IAD-CL-PCN Sema5b Glut',
 'COAa-PAA-MEA Barhl2 Glut',
 'COAp Grxcr2 Glut',
 'CS-PRNr-DR En1 Sox2 Gaba',
 'CS-PRNr-PCG Tmem163 Otp Gaba',
 'CS-RPO Meis2 Gaba',
 'CT SUB Glut',
 'CU-ECU-SPVI Foxb1 Glut',
 'CUN Evx2 Lhx2 Glut',
 'CUN-PPN Evx2 Meis2 Glut',
 'DCO Il22 Gly-Gaba',
 'DG Glut',
 'DG-PIR Ex IMN',
 'DMH Hmx2 Gaba',
 'DMH Hmx2 Glut',
 'DMH Nkx2-4 Glut',
 'DMH Prdm13 Gaba',
 'DMH-LHA Gsx1 Gaba',
 'DMH-LHA Vgll2 Glut',
 'DMX VII Tbx20 Chol',
 'DTN-LDT-IPN Otp Pax3 Gaba',
 'ENTmv-PA-COAp Glut',
 'Endo NN',
 'GPe-SI Sox6 Cyp26b1 Gaba',
 'GPi Tbr1 Cngb3 Gaba-Glut',
 'HPF CR Glut',
 'IA Mgp Gaba',
 'IC Six3 En2 Gaba',
 'IC Tfap2d Maf Glut',
 'IF-RL-CLI-PAG Foxa1 Glut',
 'IO Fgl2 Glut',
 'IPN Otp Crisp1 Gaba',
 'IPN-LDT Vsx2 Nkx6-1 Glut',
 'IT AON-TT-DP Glut',
 'IT EP-CLA Glut',
 'L2 IT ENT-po Glut',
 'L2 IT PPP-APr Glut',
 'L2/3 IT CTX Glut',
 'L2/3 IT ENT Glut',
 'L2/3 IT PIR-ENTl Glut',
 'L2/3 IT PPP Glut',
 'L2/3 IT RSP Glut',
 'L4 RSP-ACA Glut',
 'L4/5 IT CTX Glut',
 'L5 ET CTX Glut',
 'L5 IT CTX Glut',
 'L5 NP CTX Glut',
 'L5/6 IT TPE-ENT Glut',
 'L6 CT CTX Glut',
 'L6 IT CTX Glut',
 'L6b CTX Glut',
 'L6b EPd Glut',
 'L6b/CT ENT Glut',
 'LA-BLA-BMA-PA Glut',
 'LDT Vsx2 Nkx6-1 Nfib Glut',
 'LDT-DTN Gata3 Nfix Gaba',
 'LDT-PCG St18 Gaba',
 'LDT-PCG Vsx2 Lhx4 Glut',
 'LDT-PCG-CS Gata3 Lhx1 Gaba',
 'LGv-SPFp-SPFm Nkx2-2 Tcf7l2 Gaba',
 'LGv-ZI Otx2 Gaba',
 'LH Pou4f1 Sox1 Glut',
 'LHA Barhl2 Glut',
 'LHA Pmch Glut',
 'LHA-AHN-PVH Otp Trh Glut',
 'LHA-MEA Otp Glut',
 'LSX Nkx2-1 Gaba',
 'LSX Otx2 Gaba',
 'LSX Prdm12 Slit2 Gaba',
 'LSX Prdm12 Zeb2 Gaba',
 'LSX Sall3 Lmo1 Gaba',
 'LSX Sall3 Pax6 Gaba',
 'Lamp5 Gaba',
 'Lamp5 Lhx6 Gaba',
 'MB-MY Tph2 Glut-Sero',
 'MB-ant-ve Dmrta2 Glut',
 'MDRN Hoxb5 Ebf2 Gly-Gaba',
 'MEA Otp Foxp2 Glut',
 'MEA Slc17a7 Glut',
 'MEA-BST Lhx6 Nfib Gaba',
 'MEA-BST Lhx6 Nr2e1 Gaba',
 'MEA-BST Lhx6 Sp9 Gaba',
 'MEA-BST Otp Zic2 Glut',
 'MEA-BST Sox6 Gaba',
 'MEA-COA-BMA Ccdc42 Glut',
 'MG-POL-SGN Nts Glut',
 'MH Tac2 Glut',
 'MM-ant Foxb1 Glut',
 'MPN-MPO-LPO Lhx6 Zfhx3 Gaba',
 'MPN-MPO-PVpo Hmx2 Glut',
 'MPO-ADP Lhx8 Gaba',
 'MRN Pou3f1 C1ql4 Glut',
 'MRN-VTN-PPN Pax5 Cdh23 Gaba',
 'MS-SF Bsx Glut',
 'MV Nkx6-1 Gly-Gaba',
 'MV Pax6 Gly-Gaba',
 'MV-SPIV Phox2b Ebf3 Lbx1 Glut',
 'MV-SPIV Zic4 Neurod2 Glut',
 'MV-SPIV-PRP Dmbx1 Gly-Gaba',
 'MY Lhx1 Gly-Gaba',
 'MY Prox1 Lmo7 Gly-Gaba',
 'Microglia NN',
 'ND-INC Foxd2 Glut',
 'NDB-SI-MA-STRv Lhx8 Gaba',
 'NDB-SI-ant Prdm12 Gaba',
 'NI-RPO Gata3 Nr4a2 Gaba',
 'NLL Gata3 Gly-Gaba',
 'NLL-SOC Spp1 Glut',
 'NP SUB Glut',
 'NTS Dbh Glut',
 'NTS Phox2b Glut',
 'NTS-MDRNd Prox1 Zic1 Gly-Gaba',
 'NTS-PARN Neurod2 Gly-Gaba',
 'OB Dopa-Gaba',
 'OB Eomes Ms4a15 Glut',
 'OB Trdn Gaba',
 'OB-STR-CTX Inh IMN',
 'OB-in Frmd7 Gaba',
 'OB-out Frmd7 Gaba',
 'OPC NN',
 'OT D3 Folh1 Gaba',
 'Oligo NN',
 'PAG Pou4f1 Bnc2 Glut',
 'PAG Pou4f1 Ebf2 Glut',
 'PAG Pou4f2 Glut',
 'PAG Pou4f2 Mesi2 Glut',
 'PAG Pou4f3 Glut',
 'PAG Ucn Glut',
 'PAG-MRN Pou3f1 Glut',
 'PAG-MRN Tfap2b Glut',
 'PAG-MRN-RN Foxa2 Gaba',
 'PAG-ND-PCG Onecut1 Gaba',
 'PAG-PPN Pax5 Sox21 Gaba',
 'PAG-RN Nkx2-2 Otx1 Gaba',
 'PAG-SC Neurod2 Meis2 Glut',
 'PAG-SC Pou4f1 Zic1 Glut',
 'PAL-STR Gaba-Chol',
 'PARN-MDRNd-NTS Gbx2 Gly-Gaba',
 'PAS-MV Ebf2 Gly-Gaba',
 'PB Evx2 Glut',
 'PB Lmx1a Glut',
 'PB Pax5 Glut',
 'PB-NTS Phox2b Ebf3 Lmx1b Glut',
 'PCG-PRNr Vsx2 Nkx6-1 Glut',
 'PDTg-PCG Pax6 Gaba',
 'PF Fzd5 Glut',
 'PG-TRN-LRN Fat2 Glut',
 'PGRN-PARN-MDRN Hoxb5 Glut',
 'PH Pitx2 Glut',
 'PH-LHA Foxb1 Glut',
 'PH-SUM Foxa1 Glut',
 'PH-an Pitx2 Glut',
 'PH-ant-LHA Otp Bsx Glut',
 'PMd-LHA Foxb1 Glut',
 'PMv-TMv Pitx2 Glut',
 'POR Gata3 Gly-Gaba',
 'PPN-CUN-PCG Otp En1 Gaba',
 'PRC-PAG Pax6 Glut',
 'PRC-PAG Tcf7l2 Irx2 Glut',
 'PRNc Otp Gly-Gaba',
 'PRNc Prox1 Brs3 Gly-Gaba',
 'PRNc-NI-SG-RPO Vsx2 Nr4a2 Glut',
 'PRNc-PARN Tlx1 Glut',
 'PRNr Otp Nfib Glut',
 'PRP Otp Gly-Gaba',
 'PRP-NI-PRNc-GRN Otp Glut',
 'PRT Mecom Gaba',
 'PRT Tcf7l2 Gaba',
 'PSV Pvalb Lhx2 Glut',
 'PVH-SO-PVa Otp Glut',
 'PVHd Gsc Gaba',
 'PVHd-DMH Lhx6 Gaba',
 'PVHd-SBPV Six3 Prox1 Gaba',
 'PVR Six3 Sox3 Gaba',
 'PVT-PT Ntrk1 Glut',
 'PVpo-VMPO-MPN Hmx2 Gaba',
 'Peri NN',
 'Pvalb Gaba',
 'Pvalb chandelier Gaba',
 'RE-Xi Nox4 Glut',
 'RHP-COA Ndnf Gaba',
 'RT-ZI Gnb3 Gaba',
 'SBPV-PVa Six6 Satb2 Gaba',
 'SC Bnc2 Glut',
 'SC Lef1 Otx2 Gaba',
 'SC Otx2 Gcnt4 Gaba',
 'SC Tnnt1 Gli3 Gaba',
 'SC-PAG Lef1 Emx2 Gaba',
 'SCH Six6 Cdc14a Gaba',
 'SCdg-PAG Tfap2b Glut',
 'SCig Foxb1 Glut',
 'SCig Foxb1 Otx2 Glut',
 'SCig Tfap2b Chrnb3 Glut',
 'SCig-an-PPT Foxb1 Glut',
 'SCiw Pitx2 Glut',
 'SCm-PAG Cdh23 Gaba',
 'SCop Pou4f2 Neurod2 Glut',
 'SCop Sln Glut',
 'SCs Dmbx1 Gaba',
 'SCs Lef1 Gli3 Gaba',
 'SCs Pax7 Nfia Gaba',
 'SCsg Gabrr2 Gaba',
 'SCsg Pde5a Glut',
 'SI-MA-ACB Ebf1 Bnc2 Gaba',
 'SI-MA-LPO-LHA Skor1 Glut',
 'SI-MPO-LPO Lhx8 Gaba',
 'SNc-VTA-RAmb Foxa1 Dopa',
 'SNr Six3 Gaba',
 'SNr-VTA Pax5 Npas1 Gaba',
 'SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut',
 'SPVC Mafa Glut',
 'SPVI-SPVC Sall3 Lhx1 Gly-Gaba',
 'SPVI-SPVC Sall3 Nfib Gly-Gaba',
 'SPVI-SPVC Tlx3 Ebf3 Glut',
 'SPVO Mafa Meis2 Glut',
 'STN-PSTN Pitx2 Glut',
 'STR D1 Gaba',
 'STR D1 Sema5a Gaba',
 'STR D2 Gaba',
 'STR Lhx8 Gaba',
 'STR Prox1 Lhx6 Gaba',
 'STR-PAL Chst9 Gaba',
 'SUB-ProS Glut',
 'Sncg Gaba',
 'Sst Chodl Gaba',
 'Sst Gaba',
 'TH Prkcd Grin2c Glut',
 'TMv-PMv Tbx3 Hist-Gaba',
 'TRS-BAC Sln Glut',
 'TU-ARH Otp Six6 Gaba',
 'VCO Mafa Meis2 Glut',
 'VLMC NN',
 'VMH Fezf1 Glut',
 'VMH Nr5a1 Glut',
 'Vip Gaba',
 'ZI Pax6 Gaba'}

In [7]:
meta_data.groupby('SubClass').size()

SubClass
ABC NN                 484
ACB-BST-FS D1 Gaba     449
AD Serpinb7 Glut       209
ADP-MPO Trp73 Glut     172
AHN Onecut3 Gaba       410
                      ...
VLMC NN               1110
VMH Fezf1 Glut         286
VMH Nr5a1 Glut         860
Vip Gaba              1662
ZI Pax6 Gaba          1970
Length: 274, dtype: int64

In [8]:
meta_data['Celltype.l1'] = meta_data['Class']

In [25]:
meta_data

,cell,mCCCFrac,mCGFrac,mCHFrac,FinalmCReads,DissectionRegion,Plate,Col384,Row384,Slice,...,PassBasicQC,PlateNormCov,CEMBARegion,MajorRegion,SubRegion,CellGroup,SubClass,Class,NeuroTransmitters,Celltype.l1
0,10A_M_1,0.008874,0.819390,0.036336,1073981.0,RSP-4,CEMBA190423_10A_1,0,1,10,...,True,0.834409,10A,Isocortex,RSP,c18_c4_c1_c1_r0,L6b CTX Glut,NP-CT-L6b Glut,Glut,Neuron
1,10A_M_100,0.007105,0.762382,0.019705,1108484.0,RSP-4,CEMBA190423_10A_2,0,3,10,...,True,0.842048,10A,Isocortex,RSP,c24_c0_c0_c0_r2,L2/3 IT RSP Glut,IT-ET Glut,Glut,Neuron
2,10A_M_1000,0.006450,0.744689,0.016373,1443814.0,RSP-4,CEMBA190423_10A_4,7,5,10,...,True,1.031215,10A,Isocortex,RSP,c24_c0_c0_c0_r2,L2/3 IT RSP Glut,IT-ET Glut,Glut,Neuron
3,10A_M_1001,0.007433,0.780743,0.029361,1372174.0,RSP-4,CEMBA190423_10A_3,8,4,10,...,True,0.942444,10A,Isocortex,RSP,c2_c3_c4_c2_r0,L6 CT CTX Glut,NP-CT-L6b Glut,Glut,Neuron
4,10A_M_1002,0.006215,0.741165,0.018129,1650777.0,RSP-4,CEMBA190423_10A_3,8,5,10,...,True,1.133796,10A,Isocortex,RSP,c24_c0_c0_c0_r2,L2/3 IT RSP Glut,IT-ET Glut,Glut,Neuron
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301621,17A_M_3051,0.007412,0.747842,0.018610,1559491.0,CB-4,CEMBA210812_17A_4,1,14,17,...,True,1.090938,17A,CB,CBX,c21_c5_c2_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba,Neuron
301622,17A_M_3052,0.008806,0.830814,0.043916,1219087.0,CB-4,CEMBA210812_17A_4,0,15,17,...,True,0.852810,17A,CB,CBX,c36_c1_c0_c0_r1,CBX Golgi Gly-Gaba,CB GABA,Gly-Gaba,Neuron
301623,17A_M_3053,0.006352,0.768759,0.023178,1723321.0,CB-4,CEMBA210812_17A_4,12,15,17,...,True,1.205545,17A,CB,CBX,c21_c5_c0_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba,Neuron
301624,17A_M_3054,0.006006,0.755818,0.018815,1673963.0,CB-4,CEMBA210812_17A_4,13,15,17,...,True,1.171017,17A,CB,CBX,c21_c0_c2_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba,Neuron
301625,17A_M_3055,0.006692,0.780684,0.027004,1485227.0,CB-4,CEMBA210812_17A_4,1,15,17,...,True,1.038987,17A,CB,CBX,c21_c4_c1_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba,Neuron

In [10]:
meta_data.loc[~meta_data['SubClass'].str.contains('NN'),'Celltype.l1'] = "Neuron"

In [12]:
set(meta_data['Celltype.l1'])

{'Astro-Epen', 'Immune', 'Neuron', 'OPC-Oligo', 'Vascular'}

In [13]:
df_mcg_pfc = meta_annotated[meta_annotated.batch == 'mcg']

NameError: name 'meta_annotated' is not defined

In [40]:
df_mcg_pfc = df_mcg_pfc.dropna(how='all',axis=1)

In [41]:
df_mcg_pfc.set_index('cell',inplace=True)

In [42]:
df_mcg_pfc.shape

(5111, 38)

In [43]:
df_mcg_pfc['celltype.L1'].str.contains('Neuron')

cell
3A_M_2344    False
3A_M_2548     True
3A_M_344      True
2A_M_1788     True
2A_M_2460     True
             ...
2A_M_1628      NaN
3A_M_2218      NaN
3A_M_2530      NaN
2A_M_2243    False
2A_M_949       NaN
Name: celltype.L1, Length: 5111, dtype: object

In [44]:
df_neuron = df_mcg_pfc[df_mcg_pfc['celltype.L1']=='Neuron']

In [45]:
celltypes = df_mcg_pfc['celltype.L1'].dropna().unique()

In [ ]:
import os
out_path = "/data2st1/junyi/single_allcs"
# for celltype in celltypes:

#     if not os.path.exists(os.path.join(out_path,celltype)):
#         os.makedirs(os.path.join(out_path,celltype))
#     print(celltype)
#     df_celltype = df_mcg_pfc[df_mcg_pfc['celltype.L1']==celltype]
#     df_meta_celltype = meta_sample.loc[df_celltype.index]
#     print(df_meta_celltype.shape)

#     for index, row in df_meta_celltype.iterrows():
#         filename = row['Sample_supplementary_file_1'].split('/')[-1]
#         source_path = os.path.join("/data2st1/junyi/methlyatlas/mCseq/allcfiles/",filename)
#         target_path = os.path.join(out_path,celltype,filename)
#         os.symlink(source_path,target_path)

Immune
(13, 37)
Neuron
(4747, 37)
OPC-Oligo
(146, 37)
Astro-Epen
(61, 37)
Vascular
(16, 37)

In [ ]:
import subprocess

out_path = "/data2st1/junyi/single_allcs"

folder_path = glob.glob(out_path+'/*/')

print(folder_path)
for file_name in os.listdir(folder_path):
    if file_name.endswith(".gz") and file_name.endswith(".tsv.gz"):
        file_path = os.path.join(folder_path, file_name)
        # Create index for the TSV file
        cmd = f"allcools tabix-allc allc_path {file_path}"
        subprocess.run(cmd, shell=True)
        #print(f"Indexed {file_path} with tabix.")

['/data2st1/junyi/single_allcs/OPC-Oligo/', '/data2st1/junyi/single_allcs/Vascular/', '/data2st1/junyi/single_allcs/Neuron/', '/data2st1/junyi/single_allcs/Astro-Epen/', '/data2st1/junyi/single_allcs/Immune/']

In [13]:
df_selected_PFC = meta_sample.set_index('Sample_title').loc[df_mcg_pfc.index]

In [14]:
df_3A = df_selected_PFC[df_selected_PFC.Sample_characteristics_ch1=="cemba_id: 3A"]

In [15]:
df_2A = df_selected_PFC[df_selected_PFC.Sample_characteristics_ch1=="cemba_id: 2A"]

In [16]:
df_3A["Sample_title.1"]

cell
3A_M_2344    180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CE...
3A_M_2548    180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CE...
3A_M_344     180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CE...
3A_M_1269    180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CE...
3A_M_1622    180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CE...
                                   ...
3A_M_718     180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CE...
3A_M_975     180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CE...
3A_M_1056    180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CE...
3A_M_2218    180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CE...
3A_M_2530    180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CE...
Name: Sample_title.1, Length: 2592, dtype: object

In [51]:
files = glob.glob('/data2st1/junyi/methlyatlas/mCseq/allcfiles/*')

In [53]:
len(files)

51549

In [18]:
files_3A = (glob.glob('/data2st1/junyi/methlyatlas/mCseq/allcfiles/*3A*'))

In [19]:
files_2A = (glob.glob('/data2st1/junyi/methlyatlas/mCseq/allcfiles/*2A*'))

In [28]:
len(df_2A)

2592

In [26]:
len(files_2A)

2520

In [29]:
df_2A = df_selected_PFC[df_selected_PFC.Sample_characteristics_ch1=="cemba_id: 2A"]

In [21]:
values_2A = df_2A.Sample_supplementary_file_1.values

In [22]:
values_2A

array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3786nnn/GSM3786376/suppl/GSM3786376_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_G9_AD010_indexed.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3787nnn/GSM3787059/suppl/GSM3787059_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_G6_AD004_indexed.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3786nnn/GSM3786694/suppl/GSM3786694_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_C5_AD008_indexed.tsv.gz',
       ...,
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3786nnn/GSM3786220/suppl/GSM3786220_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_F12_AD002_indexed.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3786nnn/GSM3786843/suppl/GSM3786843_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E12_AD008_indexed.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3788nnn/GSM3788158/suppl/GSM3788158_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_E12_AD006_indexed.tsv.gz'],
      dtype=object)

In [83]:
filename = f"/data2st1/junyi/methlyatlas/mCseq/allcfiles/part_2A.txt"
with open(filename, 'w') as file:
    for element in values_2A:
        file.write(f"{element}\n")
print(f"Part 2a written to {filename}")

Part 2a written to /data2st1/junyi/methlyatlas/mCseq/allcfiles/part_2A.txt

In [14]:
PFC_AMY_subregions = ['MOs','PL,ORB','PL,ACA,ILA','CTXsp,sAMY']
selected_cells = meta_data[(meta_data.SubRegion.isin(PFC_AMY_subregions)) | (meta_data.MajorRegion.isin(["HPF"]))].index
selected_meta = meta_data.loc[selected_cells]

In [22]:
selected_meta['Region'].value_counts()

HPF          33016
Isocortex    12275
CTXsp         8213
Name: Region, dtype: int64

In [23]:
selected_meta['Region'] = selected_meta['MajorRegion'].replace({
    'Isocortex':'PFC',
    'CTXsp':'AMY'
})

In [26]:
df_meta_sn = pd.read_csv('/data2st2/junyi/output/stg1028/combined_SUS_meta.csv',index_col=0)

/tmp/ipykernel_3948905/3993205790.py:1: DtypeWarning: Columns (56,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df_meta_sn = pd.read_csv('/data2st2/junyi/output/stg1028/combined_SUS_meta.csv',index_col=0)

In [27]:
df_meta_sn

,sample,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,...,celltype.L1_old,Neurotransmitter_celltype_old,Neurotransmitter_celltype,celltype.L1,celltype.L2,predict.subclass,umap_seurat_1,umap_seurat_2,celltype,Neurotransmitter
AAACCCAAGATTGGGC-1HPF_beirui_CS1-1,CS1-1_HPF_beirui,2135,7.666690,4546.0,8.422223,32.556093,38.957325,46.964364,61.680598,6.0,...,NaN,NaN,Glutamatergic,Glut,HPF CA1 Glut,016 CA1-ProS Glut,3.822287,-6.543656,HPF CA1 Glut,Glut
AAACCCAAGCACCGAA-1HPF_beirui_CS1-1,CS1-1_HPF_beirui,2609,7.867106,5461.0,8.605571,27.082952,33.437099,41.182934,55.264604,37.0,...,NaN,NaN,Glutamatergic,Glut,HPF Subiculum CT Glut,031 CT SUB Glut,8.710694,2.023970,HPF Subiculum CT Glut,Glut
AAACCCAAGCATTGAA-1HPF_beirui_CS1-1,CS1-1_HPF_beirui,2599,7.863267,5909.0,8.684401,33.474361,39.279066,46.708411,59.299374,2.0,...,NaN,NaN,Glutamatergic,Glut,HPF CA1 Glut,016 CA1-ProS Glut,3.832288,-5.548922,HPF CA1 Glut,Glut
AAACCCAAGCTCCATA-1HPF_beirui_CS1-1,CS1-1_HPF_beirui,1064,6.970730,1631.0,7.397562,30.165543,36.296750,47.026364,65.419988,8.0,...,NaN,NaN,NN,Oligo,MOL-1,NN,1.925428,-0.951999,MOL-1,NN
AAACCCAAGGCACAAC-1HPF_beirui_CS1-1,CS1-1_HPF_beirui,2394,7.781139,5532.0,8.618485,34.743312,40.744758,48.228489,61.297903,4.0,...,NaN,NaN,Glutamatergic,Glut,HPF CA1 Glut,016 CA1-ProS Glut,7.343683,-6.254092,HPF CA1 Glut,Glut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGCATCAGTCA-1HPF_beirui_FC70A,FC70A_HPF_beirui,1742,7.463363,3157.0,8.057694,30.566994,36.838771,44.916060,60.658853,8.0,...,OPC-Oligo,NN,NN,OPC,OPC,NN,-9.804445,2.548478,OPC,NN
TTTGTTGGTATCACGT-1HPF_beirui_FC70A,FC70A_HPF_beirui,1883,7.541152,3946.0,8.280711,34.439939,40.851495,49.518500,64.951850,0.0,...,Neuron,Glutamatergic,Glutamatergic,Glut,HPF CA1 Glut,016 CA1-ProS Glut,4.396968,-7.370695,HPF CA1 Glut,Glut
TTTGTTGGTCGAGATG-1HPF_beirui_FC70A,FC70A_HPF_beirui,2851,7.955776,7158.0,8.876125,35.861973,41.771445,49.105896,61.609388,4.0,...,Neuron,Glutamatergic,Glutamatergic,Glut,HPF CA3 Glut,017 CA3 Glut,2.931614,11.133230,HPF CA3 Glut,Glut
TTTGTTGGTCGTATGT-1HPF_beirui_FC70A,FC70A_HPF_beirui,3111,8.043021,10089.0,9.219300,44.949945,50.381604,56.705323,67.281197,3.0,...,Neuron,GABAergic,GABAergic,GABA,HPF Pvalb GABA,052 Pvalb Gaba,-2.245146,7.841974,HPF Pvalb GABA,GABA
TTTGTTGTCTCCCAAC-1HPF_beirui_FC70A,FC70A_HPF_beirui,3354,8.118207,9648.0,9.174609,33.893035,40.723466,48.497098,61.308043,6.0,...,NaN,NaN,GABAergic,GABA,HPF Lamp5 GABA,050 Lamp5 Lhx6 Gaba,2.906109,4.015967,HPF Lamp5 GABA,GABA

In [24]:
selected_meta

,cell,mCCCFrac,mCGFrac,mCHFrac,FinalmCReads,DissectionRegion,Plate,Col384,Row384,Slice,...,PlateNormCov,CEMBARegion,MajorRegion,SubRegion,CellGroup,SubClass,Class,NeuroTransmitters,Celltype.l1,Region
6944,10E_M_0,0.008198,0.822633,0.041640,1626504.0,CA-iii,CEMBA190625_10E_1,0,0,10,...,1.057864,10E,HPF,CA,c6_c9_c2_c0_r0,Sst Gaba,CTX-MGE GABA,Gaba,Neuron,HPF
6945,10E_M_1,0.006019,0.743035,0.024127,2009998.0,CA-iii,CEMBA190625_10E_1,0,1,10,...,1.307285,10E,HPF,CA,c17_c2_c1_c0_r0,CA3 Glut,IT-ET Glut,Glut,Neuron,HPF
6946,10E_M_10,0.006569,0.750172,0.027665,1383636.0,CA-iii,CEMBA190625_10E_1,19,0,10,...,0.899905,10E,HPF,CA,c17_c2_c0_c2_r0,CA3 Glut,IT-ET Glut,Glut,Neuron,HPF
6947,10E_M_101,0.006353,0.760898,0.026547,2474670.0,CA-iii,CEMBA190625_10E_1,18,3,10,...,1.609504,10E,HPF,CA,c17_c4_c0_c0_r0,CA3 Glut,IT-ET Glut,Glut,Neuron,HPF
6948,10E_M_102,0.005409,0.752980,0.019497,2430290.0,CA-iii,CEMBA190625_10E_1,19,2,10,...,1.580639,10E,HPF,CA,c13_c3_c4_c0_r0,CA1-ProS Glut,IT-ET Glut,Glut,Neuron,HPF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241936,13B_M_3063,0.006512,0.772815,0.024346,1623089.0,RHP-5,CEMBA201210_13B_3,7,14,13,...,1.128400,13B,HPF,ENT,c18_c3_c0_c1_r0,L6b/CT ENT Glut,NP-CT-L6b Glut,Glut,Neuron,HPF
241937,13B_M_3064,0.004420,0.779971,0.015408,2430961.0,RHP-5,CEMBA201210_13B_3,18,15,13,...,1.690046,13B,HPF,ENT,c3_c0_c0_c0_r4,L6 IT CTX Glut,IT-ET Glut,Glut,Neuron,HPF
241938,13B_M_3065,0.006550,0.813182,0.029592,1365307.0,RHP-5,CEMBA201210_13B_3,19,15,13,...,0.949185,13B,HPF,ENT,c2_c8_c0_c0_r0,CT SUB Glut,NP-CT-L6b Glut,Glut,Neuron,HPF
241939,13B_M_3066,0.007224,0.782155,0.029679,1188728.0,RHP-5,CEMBA201210_13B_3,6,15,13,...,0.826424,13B,HPF,ENT,c4_c13_c3_c3_r0,L2/3 IT ENT Glut,IT-ET Glut,Glut,Neuron,HPF
241940,13B_M_3067,0.006791,0.796442,0.026972,1748260.0,RHP-5,CEMBA201210_13B_3,7,15,13,...,1.215421,13B,HPF,ENT,c4_c3_c0_c0_r1,L2/3 IT ENT Glut,IT-ET Glut,Glut,Neuron,HPF

In [16]:
df_newdownload = meta_data.loc[set(meta_data.index).difference(set(selected_meta.index))]

/tmp/ipykernel_3706463/1107121446.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_newdownload = meta_data.loc[set(meta_data.index).difference(set(selected_meta.index))]

In [8]:
selected_meta

,cell,mCCCFrac,mCGFrac,mCHFrac,FinalmCReads,DissectionRegion,Plate,Col384,Row384,Slice,...,InputReads,PassBasicQC,PlateNormCov,CEMBARegion,MajorRegion,SubRegion,CellGroup,SubClass,Class,NeuroTransmitters
6944,10E_M_0,0.008198,0.822633,0.041640,1626504.0,CA-iii,CEMBA190625_10E_1,0,0,10,...,4407752,True,1.057864,10E,HPF,CA,c6_c9_c2_c0_r0,Sst Gaba,CTX-MGE GABA,Gaba
6945,10E_M_1,0.006019,0.743035,0.024127,2009998.0,CA-iii,CEMBA190625_10E_1,0,1,10,...,5524084,True,1.307285,10E,HPF,CA,c17_c2_c1_c0_r0,CA3 Glut,IT-ET Glut,Glut
6946,10E_M_10,0.006569,0.750172,0.027665,1383636.0,CA-iii,CEMBA190625_10E_1,19,0,10,...,3455260,True,0.899905,10E,HPF,CA,c17_c2_c0_c2_r0,CA3 Glut,IT-ET Glut,Glut
6947,10E_M_101,0.006353,0.760898,0.026547,2474670.0,CA-iii,CEMBA190625_10E_1,18,3,10,...,7245482,True,1.609504,10E,HPF,CA,c17_c4_c0_c0_r0,CA3 Glut,IT-ET Glut,Glut
6948,10E_M_102,0.005409,0.752980,0.019497,2430290.0,CA-iii,CEMBA190625_10E_1,19,2,10,...,7004754,True,1.580639,10E,HPF,CA,c13_c3_c4_c0_r0,CA1-ProS Glut,IT-ET Glut,Glut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241936,13B_M_3063,0.006512,0.772815,0.024346,1623089.0,RHP-5,CEMBA201210_13B_3,7,14,13,...,4132486,True,1.128400,13B,HPF,ENT,c18_c3_c0_c1_r0,L6b/CT ENT Glut,NP-CT-L6b Glut,Glut
241937,13B_M_3064,0.004420,0.779971,0.015408,2430961.0,RHP-5,CEMBA201210_13B_3,18,15,13,...,6098442,True,1.690046,13B,HPF,ENT,c3_c0_c0_c0_r4,L6 IT CTX Glut,IT-ET Glut,Glut
241938,13B_M_3065,0.006550,0.813182,0.029592,1365307.0,RHP-5,CEMBA201210_13B_3,19,15,13,...,3519958,True,0.949185,13B,HPF,ENT,c2_c8_c0_c0_r0,CT SUB Glut,NP-CT-L6b Glut,Glut
241939,13B_M_3066,0.007224,0.782155,0.029679,1188728.0,RHP-5,CEMBA201210_13B_3,6,15,13,...,2929710,True,0.826424,13B,HPF,ENT,c4_c13_c3_c3_r0,L2/3 IT ENT Glut,IT-ET Glut,Glut
241940,13B_M_3067,0.006791,0.796442,0.026972,1748260.0,RHP-5,CEMBA201210_13B_3,7,15,13,...,4366164,True,1.215421,13B,HPF,ENT,c4_c3_c0_c0_r1,L2/3 IT ENT Glut,IT-ET Glut,Glut

In [17]:
df_newdownload

,cell,mCCCFrac,mCGFrac,mCHFrac,FinalmCReads,DissectionRegion,Plate,Col384,Row384,Slice,...,InputReads,PassBasicQC,PlateNormCov,CEMBARegion,MajorRegion,SubRegion,CellGroup,SubClass,Class,NeuroTransmitters
0,10A_M_1,0.008874,0.819390,0.036336,1073981.0,RSP-4,CEMBA190423_10A_1,0,1,10,...,2252674,True,0.834409,10A,Isocortex,RSP,c18_c4_c1_c1_r0,L6b CTX Glut,NP-CT-L6b Glut,Glut
1,10A_M_100,0.007105,0.762382,0.019705,1108484.0,RSP-4,CEMBA190423_10A_2,0,3,10,...,2549478,True,0.842048,10A,Isocortex,RSP,c24_c0_c0_c0_r2,L2/3 IT RSP Glut,IT-ET Glut,Glut
2,10A_M_1000,0.006450,0.744689,0.016373,1443814.0,RSP-4,CEMBA190423_10A_4,7,5,10,...,3342484,True,1.031215,10A,Isocortex,RSP,c24_c0_c0_c0_r2,L2/3 IT RSP Glut,IT-ET Glut,Glut
3,10A_M_1001,0.007433,0.780743,0.029361,1372174.0,RSP-4,CEMBA190423_10A_3,8,4,10,...,3220214,True,0.942444,10A,Isocortex,RSP,c2_c3_c4_c2_r0,L6 CT CTX Glut,NP-CT-L6b Glut,Glut
4,10A_M_1002,0.006215,0.741165,0.018129,1650777.0,RSP-4,CEMBA190423_10A_3,8,5,10,...,3871980,True,1.133796,10A,Isocortex,RSP,c24_c0_c0_c0_r2,L2/3 IT RSP Glut,IT-ET Glut,Glut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301621,17A_M_3051,0.007412,0.747842,0.018610,1559491.0,CB-4,CEMBA210812_17A_4,1,14,17,...,4589584,True,1.090938,17A,CB,CBX,c21_c5_c2_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba
301622,17A_M_3052,0.008806,0.830814,0.043916,1219087.0,CB-4,CEMBA210812_17A_4,0,15,17,...,3510150,True,0.852810,17A,CB,CBX,c36_c1_c0_c0_r1,CBX Golgi Gly-Gaba,CB GABA,Gly-Gaba
301623,17A_M_3053,0.006352,0.768759,0.023178,1723321.0,CB-4,CEMBA210812_17A_4,12,15,17,...,4903466,True,1.205545,17A,CB,CBX,c21_c5_c0_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba
301624,17A_M_3054,0.006006,0.755818,0.018815,1673963.0,CB-4,CEMBA210812_17A_4,13,15,17,...,4773312,True,1.171017,17A,CB,CBX,c21_c0_c2_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba
301625,17A_M_3055,0.006692,0.780684,0.027004,1485227.0,CB-4,CEMBA210812_17A_4,1,15,17,...,4205502,True,1.038987,17A,CB,CBX,c21_c4_c1_c0_r1,CBX Purkinje Gaba,CB GABA,Gaba

In [49]:
sample_selected = selected_meta.merge(meta_sample, left_on='cell', right_on='Sample_title')

In [50]:
sample_selected

,cell,mCCCFrac,mCGFrac,mCHFrac,FinalmCReads,DissectionRegion,Plate,Col384,Row384,Slice,...,Sample_data_row_count,Sample_instrument_model,Sample_library_selection,Sample_library_source,Sample_library_strategy,Sample_relation,Sample_supplementary_file_1,"""ID_REF""",geo_series,Sample_supplementary_file_2
0,10E_M_0,0.008198,0.822633,0.041640,1626504.0,CA-iii,CEMBA190625_10E_1,0,0,10,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4777...,GSM4777233,GSE157868,NaN
1,10E_M_1,0.006019,0.743035,0.024127,2009998.0,CA-iii,CEMBA190625_10E_1,0,1,10,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4777...,GSM4777234,GSE157868,NaN
2,10E_M_10,0.006569,0.750172,0.027665,1383636.0,CA-iii,CEMBA190625_10E_1,19,0,10,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4777...,GSM4777238,GSE157868,NaN
3,10E_M_101,0.006353,0.760898,0.026547,2474670.0,CA-iii,CEMBA190625_10E_1,18,3,10,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4777...,GSM4777286,GSE157868,NaN
4,10E_M_102,0.005409,0.752980,0.019497,2430290.0,CA-iii,CEMBA190625_10E_1,19,2,10,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4777...,GSM4777287,GSE157868,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51531,13B_M_3063,0.006512,0.772815,0.024346,1623089.0,RHP-5,CEMBA201210_13B_3,7,14,13,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7382...,GSM7382519,GSE232768,NaN
51532,13B_M_3064,0.004420,0.779971,0.015408,2430961.0,RHP-5,CEMBA201210_13B_3,18,15,13,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7382...,GSM7382520,GSE232768,NaN
51533,13B_M_3065,0.006550,0.813182,0.029592,1365307.0,RHP-5,CEMBA201210_13B_3,19,15,13,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7382...,GSM7382521,GSE232768,NaN
51534,13B_M_3066,0.007224,0.782155,0.029679,1188728.0,RHP-5,CEMBA201210_13B_3,6,15,13,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7382...,GSM7382522,GSE232768,NaN
51535,13B_M_3067,0.006791,0.796442,0.026972,1748260.0,RHP-5,CEMBA201210_13B_3,7,15,13,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7382...,GSM7382523,GSE232768,NaN

In [66]:
import os
os.mkdir('/data2st1/junyi/single_allcs/PFC')

In [76]:
PFC_subregions = ['MOs','PL,ORB','PL,ACA,ILA']
PFC_cells = sample_selected[(sample_selected.SubRegion.isin(PFC_subregions))].index
df_meta_pfcs = sample_selected.loc[PFC_cells]

In [77]:
df_meta_pfcs

,cell,mCCCFrac,mCGFrac,mCHFrac,FinalmCReads,DissectionRegion,Plate,Col384,Row384,Slice,...,Sample_data_row_count,Sample_instrument_model,Sample_library_selection,Sample_library_source,Sample_library_strategy,Sample_relation,Sample_supplementary_file_1,"""ID_REF""",geo_series,Sample_supplementary_file_2
12858,1A_M_0,0.00424,0.76626,0.02097,1932779.0,MOs-1,CEMBA180226_1A_1,18,0,1,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3742...,GSM3742106,GSE130553,NaN
12859,1A_M_1,0.00422,0.75972,0.02032,1549132.0,MOs-1,CEMBA180226_1A_1,18,1,1,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3742...,GSM3742109,GSE130553,NaN
12860,1A_M_10,0.00426,0.77770,0.01968,2339654.0,MOs-1,CEMBA180226_1A_1,21,1,1,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3742...,GSM3742113,GSE130553,NaN
12861,1A_M_100,0.00425,0.76368,0.01855,2353156.0,MOs-1,CEMBA180226_1A_2,20,3,1,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3742...,GSM3742203,GSE130553,NaN
12862,1A_M_1000,0.00430,0.77842,0.02109,958205.0,MOs-1,CEMBA180226_1A_4,7,6,1,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3743...,GSM3743103,GSE130553,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25128,3B_M_995,0.00522,0.80631,0.02440,1664719.0,MOs-3,CEMBA180312_3B_3,19,9,3,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3843...,GSM3843464,GSE132101,NaN
25129,3B_M_996,0.00637,0.79797,0.03162,1536972.0,MOs-3,CEMBA180312_3B_4,18,8,3,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3843...,GSM3843466,GSE132101,NaN
25130,3B_M_997,0.00699,0.84993,0.03363,3572105.0,MOs-3,CEMBA180312_3B_4,18,9,3,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3843...,GSM3843468,GSE132101,NaN
25131,3B_M_998,0.00754,0.80610,0.03690,1003803.0,MOs-3,CEMBA180312_3B_4,19,8,3,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3843...,GSM3843448,GSE132101,NaN
25132,3B_M_999,0.00529,0.78287,0.02283,1496754.0,MOs-3,CEMBA180312_3B_4,19,9,3,...,0,Illumina NovaSeq 6000,other,genomic,OTHER,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3843...,GSM3843469,GSE132101,NaN

In [96]:
df_meta_pfcs.groupby('SubClass').size()

SubClass
ABC NN                     19
Astro-TE NN               189
CA2-FC-IG Glut              3
CLA-EPd-CTX Car3 Glut       6
DG-PIR Ex IMN               1
Endo NN                     6
IT AON-TT-DP Glut          29
IT EP-CLA Glut              1
L2/3 IT CTX Glut         2660
L4/5 IT CTX Glut         2358
L5 ET CTX Glut            751
L5 IT CTX Glut            515
L5 NP CTX Glut            487
L6 CT CTX Glut           1982
L6 IT CTX Glut           1187
L6b CTX Glut               61
L6b/CT ENT Glut             1
Lamp5 Gaba                306
Lamp5 Lhx6 Gaba             9
Microglia NN               72
OB-STR-CTX Inh IMN          2
OB-in Frmd7 Gaba            2
OB-out Frmd7 Gaba           1
OPC NN                     45
Oligo NN                  163
PVHd-DMH Lhx6 Gaba          1
Peri NN                    16
Pvalb Gaba                459
Pvalb chandelier Gaba      19
STR D1 Gaba                 1
STR D1 Sema5a Gaba          1
STR D2 Gaba                 1
STR-PAL Chst9 Gaba          1
Sncg Gaba                  93
Sst Chodl Gaba             17
Sst Gaba                  485
VLMC NN                    50
Vip Gaba                  275
dtype: int64

In [95]:
df_meta_hips.groupby('SubClass').size()

SubClass
ABC NN                      60
ADP-MPO Trp73 Glut           1
AVPV-MEPO-SFO Tbr1 Glut      3
Astro-NT NN                  3
Astro-TE NN                652
                          ...
Sst Gaba                   687
TH Prkcd Grin2c Glut         4
VLMC NN                    151
Vip Gaba                   168
ZI Pax6 Gaba                 1
Length: 93, dtype: int64

In [94]:
df_meta_amys.groupby('SubClass').size()

SubClass
ACB-BST-FS D1 Gaba             28
AHN-RCH-LHA Otp Fezf1 Glut      3
Astro-NT NN                    29
Astro-TE NN                   167
BST Tac2 Gaba                  16
                             ...
Sst Chodl Gaba                 41
Sst Gaba                      114
VLMC NN                        11
Vip Gaba                       51
ZI Pax6 Gaba                    7
Length: 93, dtype: int64

In [ ]:
for celltype in set(df_meta_pfcs['SubClass']):
    celltype_out_name = celltype.replace('/','-').replace(' ','_')
    print(celltype)
    df_celltype = df_meta_pfcs[df_meta_pfcs['SubClass']==celltype]
    df_celltype.set_index('cell',inplace=True)
    df_meta_celltype = meta_sample.set_index('Sample_title').loc[df_celltype.index]
    print(df_meta_celltype.shape)
    df_meta_celltype['fname'] = df_meta_celltype['Sample_supplementary_file_1'].str.split('/').str[-1]
    df_meta_celltype['fname'] = "/data2st1/junyi/methlyatlas/mCseq/allcfiles/"+ df_meta_celltype['fname']
    df_meta_celltype['fname'].to_csv(f'/data2st1/junyi/single_allcs/PFC/{celltype_out_name}.txt',header=None,index=False)

Lamp5 Lhx6 Gaba
(9, 37)
L4/5 IT CTX Glut
(2358, 37)
PVHd-DMH Lhx6 Gaba
(1, 37)
OB-out Frmd7 Gaba
(1, 37)
Microglia NN
(72, 37)
L5 ET CTX Glut
(751, 37)
STR-PAL Chst9 Gaba
(1, 37)
IT AON-TT-DP Glut
(29, 37)
STR D2 Gaba
(1, 37)
Oligo NN
(163, 37)
ABC NN
(19, 37)
Vip Gaba
(275, 37)
CLA-EPd-CTX Car3 Glut
(6, 37)
L6 IT CTX Glut
(1187, 37)
CA2-FC-IG Glut
(3, 37)
VLMC NN
(50, 37)
Endo NN
(6, 37)
Sncg Gaba
(93, 37)
L6 CT CTX Glut
(1982, 37)
L5 IT CTX Glut
(515, 37)
Pvalb chandelier Gaba
(19, 37)
Sst Gaba
(485, 37)
OPC NN
(45, 37)
Pvalb Gaba
(459, 37)
OB-in Frmd7 Gaba
(2, 37)
L6b CTX Glut
(61, 37)
Lamp5 Gaba
(306, 37)
OB-STR-CTX Inh IMN
(2, 37)
Sst Chodl Gaba
(17, 37)
STR D1 Gaba
(1, 37)
DG-PIR Ex IMN
(1, 37)
Peri NN
(16, 37)
L6b/CT ENT Glut
(1, 37)
Astro-TE NN
(189, 37)
STR D1 Sema5a Gaba
(1, 37)
L5 NP CTX Glut
(487, 37)
IT EP-CLA Glut
(1, 37)
L2/3 IT CTX Glut
(2660, 37)

In [110]:
PFC_na_list = []
for celltype in set(df_meta_pfcs['Celltype.l1']):
    if not os.path.exists(f'/data2st1/junyi/single_allcs/PFC/{celltype}'):
        os.mkdir(f'/data2st1/junyi/single_allcs/PFC/{celltype}')

    print(celltype)
    df_celltype = df_meta_pfcs[df_meta_pfcs['Celltype.l1']==celltype]

    df_celltype.set_index('cell',inplace=True)
    df_meta_celltype = meta_sample.set_index('Sample_title').loc[df_celltype.index]
    print(df_meta_celltype.shape)
    df_meta_celltype.to_csv(f'/data2st1/junyi/single_allcs/PFC/{celltype}.csv')

    for index, row in df_meta_celltype.iterrows():
        filename = row['Sample_supplementary_file_1'].split('/')[-1]

        source_path = os.path.join("/data2st1/junyi/methlyatlas/mCseq/allcfiles/",filename)
        target_path = f'/data2st1/junyi/single_allcs/PFC/{celltype}/'+filename
        if os.path.exists(source_path):
            os.symlink(source_path,target_path)

            tbi_source = glob.glob(f'/data2st1/junyi/single_allcs/*/{filename}.tbi')
            tbi_target = os.path.join(out_path,celltype,filename+'.tbi')
        else:
            PFC_na_list.append(row['Sample_supplementary_file_1'])

Immune
(72, 37)
Neuron
(11715, 37)
Astro-Epen
(189, 37)
OPC-Oligo
(208, 37)
Vascular
(91, 37)

In [114]:
with open('/data2st1/junyi/single_allcs/PFC/nalist.txt', 'w') as file:
    for element in PFC_na_list:
        file.write(f"{element}\n")

In [78]:
AMY_subregions = ['CTXsp,sAMY']
AMY_cells = sample_selected[(sample_selected.SubRegion.isin(AMY_subregions))].index
df_meta_amys = sample_selected.loc[AMY_cells]

In [ ]:
for celltype in set(df_meta_amys['SubClass']):
    celltype_out_name = celltype.replace('/','-').replace(' ','_')
    print(celltype)
    df_celltype = df_meta_amys[df_meta_amys['SubClass']==celltype]
    df_celltype.set_index('cell',inplace=True)
    df_meta_celltype = meta_sample.set_index('Sample_title').loc[df_celltype.index]
    print(df_meta_celltype.shape)
    df_meta_celltype['fname'] = df_meta_celltype['Sample_supplementary_file_1'].str.split('/').str[-1]
    df_meta_celltype['fname'] = "/data2st1/junyi/methlyatlas/mCseq/allcfiles/"+ df_meta_celltype['fname']
    df_meta_celltype['fname'].to_csv(f'/data2st1/junyi/single_allcs/AMY/{celltype_out_name}.txt',header=None,index=False)

RHP-COA Ndnf Gaba
(55, 37)
PVH-SO-PVa Otp Glut
(8, 37)
PMd-LHA Foxb1 Glut
(1, 37)
Microglia NN
(82, 37)
GPe-SI Sox6 Cyp26b1 Gaba
(20, 37)
STR Lhx8 Gaba
(21, 37)
AHN-RCH-LHA Otp Fezf1 Glut
(3, 37)
STR D2 Gaba
(163, 37)
CLA-EPd-CTX Car3 Glut
(11, 37)
L6 CT CTX Glut
(11, 37)
CA1-ProS Glut
(17, 37)
HPF CR Glut
(3, 37)
PH-ant-LHA Otp Bsx Glut
(2, 37)
Pvalb chandelier Gaba
(16, 37)
OB-in Frmd7 Gaba
(1, 37)
Pvalb Gaba
(86, 37)
DG Glut
(9, 37)
MEA-COA-BMA Ccdc42 Glut
(817, 37)
RT-ZI Gnb3 Gaba
(2, 37)
STR D1 Sema5a Gaba
(74, 37)
LDT-PCG Vsx2 Lhx4 Glut
(1, 37)
COAa-PAA-MEA Barhl2 Glut
(426, 37)
L2/3 IT CTX Glut
(1, 37)
SUB-ProS Glut
(1, 37)
L4/5 IT CTX Glut
(2, 37)
SCsg Gabrr2 Gaba
(1, 37)
Astro-NT NN
(29, 37)
PVHd-DMH Lhx6 Gaba
(1, 37)
LHA-MEA Otp Glut
(11, 37)
MEA Otp Foxp2 Glut
(97, 37)
MEA Slc17a7 Glut
(359, 37)
MEA-BST Sox6 Gaba
(382, 37)
Vip Gaba
(51, 37)
MEA-BST Lhx6 Sp9 Gaba
(239, 37)
L6 IT CTX Glut
(1, 37)
Endo NN
(4, 37)
VLMC NN
(11, 37)
Sncg Gaba
(32, 37)
CEA-AAA-BST Six3 Sp9 Gaba
(411, 37)
MPO-ADP Lhx8 Gaba
(4, 37)
OB-STR-CTX Inh IMN
(11, 37)
CEA-BST Rai14 Pdyn Crh Gaba
(30, 37)
L6b EPd Glut
(67, 37)
Sst Chodl Gaba
(41, 37)
LHA Barhl2 Glut
(4, 37)
STR D1 Gaba
(192, 37)
MEA-BST Lhx6 Nr2e1 Gaba
(105, 37)
ZI Pax6 Gaba
(7, 37)
NDB-SI-ant Prdm12 Gaba
(9, 37)
Peri NN
(14, 37)
PH-LHA Foxb1 Glut
(5, 37)
Astro-TE NN
(167, 37)
Lamp5 Lhx6 Gaba
(20, 37)
COAp Grxcr2 Glut
(37, 37)
STR Prox1 Lhx6 Gaba
(66, 37)
L2/3 IT PIR-ENTl Glut
(107, 37)
BST Tac2 Gaba
(16, 37)
CEA-BST Gal Avp Gaba
(10, 37)
IA Mgp Gaba
(87, 37)
SI-MA-ACB Ebf1 Bnc2 Gaba
(6, 37)
PB-NTS Phox2b Ebf3 Lmx1b Glut
(5, 37)
SPVI-SPVC Tlx3 Ebf3 Glut
(3, 37)
STR-PAL Chst9 Gaba
(819, 37)
IT AON-TT-DP Glut
(8, 37)
PGRN-PARN-MDRN Hoxb5 Glut
(1, 37)
BST-SI-AAA Six3 Slc22a3 Gaba
(34, 37)
NP SUB Glut
(1, 37)
MEA-BST Lhx6 Nfib Gaba
(142, 37)
OPC NN
(99, 37)
L6b CTX Glut
(3, 37)
Lamp5 Gaba
(73, 37)
MPN-MPO-LPO Lhx6 Zfhx3 Gaba
(6, 37)
DG-PIR Ex IMN
(28, 37)
LA-BLA-BMA-PA Glut
(976, 37)
MEA-BST Otp Zic2 Glut
(54, 37)
SI-MA-LPO-LHA Skor1 Glut
(109, 37)
SPA-SPFm-SPFp-POL-PIL-PoT Sp9 Glut
(3, 37)
CU-ECU-SPVI Foxb1 Glut
(2, 37)
CEA-BST Six3 Cyp26b1 Gaba
(405, 37)
Oligo NN
(224, 37)
NDB-SI-MA-STRv Lhx8 Gaba
(114, 37)
PH Pitx2 Glut
(1, 37)
L2/3 IT ENT Glut
(1, 37)
ACB-BST-FS D1 Gaba
(28, 37)
Sst Gaba
(114, 37)
CEA-BST Ebf1 Pdyn Gaba
(301, 37)
SI-MPO-LPO Lhx8 Gaba
(35, 37)
PVpo-VMPO-MPN Hmx2 Gaba
(1, 37)
PAL-STR Gaba-Chol
(24, 37)
BST-MPN Six3 Nrgn Gaba
(30, 37)
L6b/CT ENT Glut
(1, 37)
IT EP-CLA Glut
(90, 37)
CA3 Glut
(11, 37)

In [138]:
AMY_subregions = ['CTXsp,sAMY']
AMY_cells = sample_selected[(sample_selected.SubRegion.isin(AMY_subregions))].index
df_meta_amys = sample_selected.loc[AMY_cells]
AMY_na_list = []
#os.mkdir('/data2st1/junyi/single_allcs/AMY')
for celltype in set(df_meta_amys['Celltype.l1']):
    if not os.path.exists(f'/data2st1/junyi/single_allcs/AMY/{celltype}'):
        os.mkdir(f'/data2st1/junyi/single_allcs/AMY/{celltype}')

    print(celltype)
    df_celltype = df_meta_amys[df_meta_amys['Celltype.l1']==celltype]

    df_celltype.set_index('cell',inplace=True)

    df_meta_celltype = meta_sample.set_index('Sample_title').loc[df_celltype.index]
    print(df_meta_celltype.shape)

    for index, row in df_meta_celltype.iterrows():
        filename = row['Sample_supplementary_file_1'].split('/')[-1]

        source_path = os.path.join("/data2st1/junyi/methlyatlas/mCseq/allcfiles/",filename)
        target_path = f'/data2st1/junyi/single_allcs/AMY/{celltype}/'+filename
        if os.path.exists(source_path):
            os.symlink(source_path,target_path)

            tbi_source = glob.glob(f'/data2st1/junyi/single_allcs/*/{filename}.tbi')
            tbi_target = os.path.join(out_path,celltype,filename+'.tbi')
        else:
            AMY_na_list.append(row['Sample_supplementary_file_1'])

with open('/data2st1/junyi/single_allcs/AMY/nalist.txt', 'w') as file:
    for element in AMY_na_list:
        file.write(f"{element}\n")

Immune
(82, 37)
Neuron
(7583, 37)
Astro-Epen
(196, 37)
OPC-Oligo
(323, 37)
Vascular
(29, 37)

In [131]:
os.path.exists(source_path)

True

In [81]:
HIP_subregions = ['HPF']
HIP_cells = sample_selected[(sample_selected.MajorRegion.isin(HIP_subregions))].index
df_meta_hips = sample_selected.loc[HIP_cells]
df_meta_hips.shape

(31048, 61)

In [115]:
for celltype in set(df_meta_hips['SubClass']):
    celltype_out_name = celltype.replace('/','-').replace(' ','_')
    print(celltype)
    df_celltype = df_meta_hips[df_meta_hips['SubClass']==celltype]
    df_celltype.set_index('cell',inplace=True)
    df_meta_celltype = meta_sample.set_index('Sample_title').loc[df_celltype.index]
    print(df_meta_celltype.shape)
    df_meta_celltype['fname'] = df_meta_celltype['Sample_supplementary_file_1'].str.split('/').str[-1]
    df_meta_celltype['fname'] = "/data2st1/junyi/methlyatlas/mCseq/allcfiles/"+ df_meta_celltype['fname']
    df_meta_celltype['fname'].to_csv(f'/data2st1/junyi/single_allcs/HIP/{celltype_out_name}.txt',header=None,index=False)

RHP-COA Ndnf Gaba
(201, 37)
Microglia NN
(299, 37)
MG-POL-SGN Nts Glut
(3, 37)
L4 RSP-ACA Glut
(6, 37)
MH Tac2 Glut
(1, 37)
STR D2 Gaba
(2, 37)
L2/3 IT PPP Glut
(951, 37)
MS-SF Bsx Glut
(3, 37)
CLA-EPd-CTX Car3 Glut
(170, 37)
L6 CT CTX Glut
(362, 37)
CB Granule Glut
(3, 37)
CA1-ProS Glut
(4090, 37)
HPF CR Glut
(54, 37)
Pvalb chandelier Gaba
(47, 37)
Pvalb Gaba
(505, 37)
DG Glut
(6836, 37)
LSX Sall3 Pax6 Gaba
(1, 37)
MEA-COA-BMA Ccdc42 Glut
(1, 37)
OB Eomes Ms4a15 Glut
(1, 37)
CHOR NN
(21, 37)
STR D1 Sema5a Gaba
(3, 37)
L5 NP CTX Glut
(38, 37)
COAa-PAA-MEA Barhl2 Glut
(70, 37)
L2/3 IT CTX Glut
(549, 37)
PRT Tcf7l2 Gaba
(1, 37)
SUB-ProS Glut
(507, 37)
L4/5 IT CTX Glut
(379, 37)
ADP-MPO Trp73 Glut
(1, 37)
AVPV-MEPO-SFO Tbr1 Glut
(3, 37)
Astro-NT NN
(3, 37)
ENTmv-PA-COAp Glut
(298, 37)
MEA Slc17a7 Glut
(28, 37)
MEA-BST Sox6 Gaba
(1, 37)
Vip Gaba
(168, 37)
L6 IT CTX Glut
(89, 37)
VLMC NN
(151, 37)
Endo NN
(59, 37)
Sncg Gaba
(198, 37)
PAG-RN Nkx2-2 Otx1 Gaba
(1, 37)
PRT Mecom Gaba
(1, 37)
CEA-AAA-BST Six3 Sp9 Gaba
(1, 37)
OB-STR-CTX Inh IMN
(120, 37)
L6b EPd Glut
(244, 37)
Sst Chodl Gaba
(34, 37)
STR D1 Gaba
(13, 37)
MEA-BST Lhx6 Nr2e1 Gaba
(3, 37)
ZI Pax6 Gaba
(1, 37)
NDB-SI-ant Prdm12 Gaba
(1, 37)
Peri NN
(43, 37)
LSX Otx2 Gaba
(1, 37)
Astro-TE NN
(652, 37)
IC Six3 En2 Gaba
(1, 37)
Lamp5 Lhx6 Gaba
(209, 37)
COAp Grxcr2 Glut
(119, 37)
STR Prox1 Lhx6 Gaba
(5, 37)
L2/3 IT PIR-ENTl Glut
(1494, 37)
STR-PAL Chst9 Gaba
(11, 37)
IT AON-TT-DP Glut
(47, 37)
LSX Sall3 Lmo1 Gaba
(5, 37)
CA2-FC-IG Glut
(578, 37)
MY Lhx1 Gly-Gaba
(1, 37)
NP SUB Glut
(285, 37)
OPC NN
(318, 37)
MEA-BST Lhx6 Nfib Gaba
(2, 37)
L6b CTX Glut
(41, 37)
Lamp5 Gaba
(213, 37)
BST-po Iigp1 Glut
(1, 37)
DG-PIR Ex IMN
(148, 37)
LSX Prdm12 Zeb2 Gaba
(25, 37)
L5/6 IT TPE-ENT Glut
(349, 37)
LA-BLA-BMA-PA Glut
(859, 37)
L2 IT PPP-APr Glut
(165, 37)
SI-MA-LPO-LHA Skor1 Glut
(1, 37)
CT SUB Glut
(93, 37)
L5 ET CTX Glut
(129, 37)
TH Prkcd Grin2c Glut
(4, 37)
L2 IT ENT-po Glut
(169, 37)
CEA-BST Six3 Cyp26b1 Gaba
(14, 37)
Oligo NN
(1115, 37)
ABC NN
(60, 37)
NDB-SI-MA-STRv Lhx8 Gaba
(1, 37)
LGv-ZI Otx2 Gaba
(4, 37)
L2/3 IT ENT Glut
(1543, 37)
L5 IT CTX Glut
(50, 37)
Sst Gaba
(687, 37)
L2/3 IT RSP Glut
(25, 37)
SNc-VTA-RAmb Foxa1 Dopa
(1, 37)
SI-MPO-LPO Lhx8 Gaba
(2, 37)
PH-SUM Foxa1 Glut
(2, 37)
PAL-STR Gaba-Chol
(1, 37)
L6b/CT ENT Glut
(1466, 37)
IT EP-CLA Glut
(396, 37)
CA3 Glut
(3191, 37)

In [ ]:
files = glob.glob('/data2st1/junyi/methlyatlas/mCseq/allcfiles/*')

In [137]:
HIP_subregions = ['HPF']
HIP_cells = sample_selected[(sample_selected.MajorRegion.isin(HIP_subregions))].index
df_meta_hips = sample_selected.loc[HIP_cells]
HIP_na_list = []
if not os.path.exists('/data2st1/junyi/single_allcs/HIP'):
    os.mkdir('/data2st1/junyi/single_allcs/HIP')
for celltype in set(df_meta_hips['Celltype.l1']):
    if not os.path.exists(f'/data2st1/junyi/single_allcs/HIP/{celltype}'):
        os.mkdir(f'/data2st1/junyi/single_allcs/HIP/{celltype}')

    print(celltype)
    df_celltype = df_meta_hips[df_meta_hips['Celltype.l1']==celltype]
    df_celltype.set_index('cell',inplace=True)
    df_meta_celltype = meta_sample.set_index('Sample_title').loc[df_celltype.index]
    print(df_meta_celltype.shape)

    for index, row in df_meta_celltype.iterrows():
        filename = row['Sample_supplementary_file_1'].split('/')[-1]

        source_path = os.path.join("/data2st1/junyi/methlyatlas/mCseq/allcfiles/",filename)
        target_path = f'/data2st1/junyi/single_allcs/HIP/{celltype}/'+filename

        if os.path.exists(source_path):
            os.symlink(source_path,target_path)

            tbi_source = glob.glob(f'/data2st1/junyi/single_allcs/*/{filename}.tbi')
            tbi_target = os.path.join(out_path,celltype,filename+'.tbi')
        else:
            HIP_na_list.append(row['Sample_supplementary_file_1'])

with open('/data2st1/junyi/single_allcs/HIP/nalist.txt', 'w') as file:
    for element in HIP_na_list:
        file.write(f"{element}\n")

Immune
(299, 37)
Neuron
(28327, 37)
Astro-Epen
(676, 37)
OPC-Oligo
(1433, 37)
Vascular
(313, 37)

In [ ]:
import os
out_path = "/data2st1/junyi/single_allcs"
for celltype in celltypes:

    if not os.path.exists(os.path.join(out_path,celltype)):
        os.makedirs(os.path.join(out_path,celltype))
    print(celltype)
    df_celltype = df_mcg_pfc[df_mcg_pfc['celltype.L1']==celltype]
    df_meta_celltype = meta_sample.loc[df_celltype.index]
    print(df_meta_celltype.shape)

    for index, row in df_meta_celltype.iterrows():
        filename = row['Sample_supplementary_file_1'].split('/')[-1]
        source_path = os.path.join("/data2st1/junyi/methlyatlas/mCseq/allcfiles/",filename)
        target_path = os.path.join(out_path,celltype,filename)
        os.symlink(source_path,target_path)

NameError: name 'celltypes' is not defined

In [61]:
tbi = glob.glob('/data2st1/junyi/single_allcs/*/*.tbi*')

In [62]:
tbi

['/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815320_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_B12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786754_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_D12_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787137_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_H5_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787651_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_F11_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787404_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_C12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789316_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_H12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787926_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_A4_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788057_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_C3_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789913_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_G12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789509_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_B4_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789995_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_H12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789298_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_G9_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787684_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_F4_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789668_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_D12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786344_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_G6_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788177_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_E4_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787989_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_B4_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789254_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_G4_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788062_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_C4_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787569_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_E12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789882_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_G10_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787730_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_G11_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786841_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E1_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816462_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_H12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786660_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_C12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789310_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_H11_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787983_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_B12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786653_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_C11_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786888_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E8_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787278_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_A7_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816428_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_G8_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816163_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_D5_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815324_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_B12_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787572_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_E12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815973_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_B12_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786310_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_G12_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816085_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_C5_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786895_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E8_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787967_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_B12_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787978_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_B12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786167_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_E5_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789050_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_E11_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788887_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_C12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787896_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_H9_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815371_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_B8_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787690_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_F5_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3785872_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_B12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815827_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_H3_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786831_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789652_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_D11_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815878_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_A10_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787745_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_G12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816145_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_D3_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786432_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_H5_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816300_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_F12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815407_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_C12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789085_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_E4_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789146_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_F12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815239_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_A11_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786693_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_C5_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786995_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_G10_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789730_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_E12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815473_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_D11_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786612_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_B6_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789658_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_D12_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786463_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_A10_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816491_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_H7_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816207_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_E11_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788379_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_A3_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787542_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_D8_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815890_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_A12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786721_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_C8_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786224_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_F12_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815981_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_B3_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786477_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_A12_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787365_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_B7_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786042_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_D12_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816443_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_H10_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786775_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_D4_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815842_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_H5_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788028_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_C12_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786106_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_D7_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786321_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_G12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815574_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_E12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786086_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_D5_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789122_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_F10_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815985_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_B12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786047_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_D12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816058_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_C12_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816224_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_E12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3785925_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_B8_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786571_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_B12_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789319_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_H12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788033_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_C12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789539_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_B8_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789793_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_E8_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3790033_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_H4_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789598_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_C4_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786147_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_E12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3788260_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_3_CEMBA180122_2A_4_F7_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789433_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_A5_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789402_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_A12_AD001_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786222_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_F12_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815891_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_A12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815501_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_D3_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787564_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_E12_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789571_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_C12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789825_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_F11_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789967_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_G8_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816060_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_C12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789504_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_B3_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3785957_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_C12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789522_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_B5_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787701_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_F6_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787754_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_G1_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786392_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_H11_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786827_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E11_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789046_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_1_CEMBA180129_3A_2_E11_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3816217_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_3_CEMBA180130_3A_4_E12_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787706_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_F7_AD004_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815319_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_B12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787316_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_B12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786950_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_F3_AD006_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789645_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_D10_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789570_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_C12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3789676_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180129_3A_3_CEMBA180129_3A_4_D3_AD007_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787479_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180122_2A_1_CEMBA180122_2A_2_D12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786830_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_E12_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3786403_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_H12_AD010_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815868_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_H8_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815877_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_H9_AD012_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3785839_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_1_CEMBA180123_2A_2_A9_AD002_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3787104_allc_180705_CEMBA_mm_P56_P63_2A_CEMBA180123_2A_3_CEMBA180123_2A_4_H12_AD008_indexed.tsv.gz.tbi',
 '/data2st1/junyi/single_allcs/OPC-Oligo/GSM3815483_allc_180215_CEMBA_mm_P56_P63_3A_CEMBA180130_3A_1_CEMBA180130_3A_2_D12_AD010_indexed.tsv.gz.tbi',

In [20]:
new_selected = df_newdownload.merge(meta_sample, left_on='cell', right_on='Sample_title')

In [21]:
values_download = new_selected.Sample_supplementary_file_1.values

In [22]:
values_download

array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6574nnn/GSM6574626/suppl/GSM6574626_allc_CEMBA190423-10A-1-CEMBA190423-10A-2-A1_ad002.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6574nnn/GSM6574627/suppl/GSM6574627_allc_CEMBA190423-10A-1-CEMBA190423-10A-2-B1_ad008.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6574nnn/GSM6574628/suppl/GSM6574628_allc_CEMBA190423-10A-3-CEMBA190423-10A-4-C4_ad012.tsv.gz',
       ...,
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7523nnn/GSM7523989/suppl/GSM7523989_CEMBA210812_17A_4-1-G10-P13.allc.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7523nnn/GSM7523990/suppl/GSM7523990_CEMBA210812_17A_4-1-G10-P14.allc.tsv.gz',
       'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7523nnn/GSM7523991/suppl/GSM7523991_CEMBA210812_17A_4-1-G10-P2.allc.tsv.gz'],
      dtype=object)

In [23]:
length = len(values_download)
parts = 10
part_length = int(length/parts)
parts_list = [values_download[i*part_length:(i+1)*part_length] for i in range(parts)]

In [24]:
parts_list

[array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6574nnn/GSM6574626/suppl/GSM6574626_allc_CEMBA190423-10A-1-CEMBA190423-10A-2-A1_ad002.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6574nnn/GSM6574627/suppl/GSM6574627_allc_CEMBA190423-10A-1-CEMBA190423-10A-2-B1_ad008.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6574nnn/GSM6574628/suppl/GSM6574628_allc_CEMBA190423-10A-3-CEMBA190423-10A-4-C4_ad012.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3824nnn/GSM3824070/suppl/GSM3824070_allc_180305_CEMBA_mm_P56_P63_1B_CEMBA180213_1B_1_CEMBA180213_1B_2_A5_AD010_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3824nnn/GSM3824071/suppl/GSM3824071_allc_180305_CEMBA_mm_P56_P63_1B_CEMBA180213_1B_1_CEMBA180213_1B_2_A5_AD012_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3824nnn/GSM3824072/suppl/GSM3824072_allc_180305_CEMBA_mm_P56_P63_1B_CEMBA180213_1B_1_CEMBA180213_1B_2_A6_AD001_indexed.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3824nnn/GSM3824073/suppl/GSM3824073_allc_180305_CEMBA_mm_P56_P63_1B_CEMBA180213_1B_1_CEMBA180213_1B_2_A6_AD002_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3824nnn/GSM3824074/suppl/GSM3824074_allc_180305_CEMBA_mm_P56_P63_1B_CEMBA180213_1B_1_CEMBA180213_1B_2_A6_AD004_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3824nnn/GSM3824075/suppl/GSM3824075_allc_180305_CEMBA_mm_P56_P63_1B_CEMBA180213_1B_1_CEMBA180213_1B_2_A6_AD006_indexed.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3771nnn/GSM3771900/suppl/GSM3771900_allc_171219_CEMBA_mm_P56_P63_4B_CEMBA171213_4B_1_CEMBA171213_4B_2_G7_AD008_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3771nnn/GSM3771902/suppl/GSM3771902_allc_171219_CEMBA_mm_P56_P63_4B_CEMBA171213_4B_1_CEMBA171213_4B_2_G7_AD010_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3771nnn/GSM3771903/suppl/GSM3771903_allc_171219_CEMBA_mm_P56_P63_4B_CEMBA171213_4B_1_CEMBA171213_4B_2_G7_AD012_indexed.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3771nnn/GSM3771905/suppl/GSM3771905_allc_171219_CEMBA_mm_P56_P63_4B_CEMBA171213_4B_1_CEMBA171213_4B_2_G8_AD001_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3771nnn/GSM3771906/suppl/GSM3771906_allc_171219_CEMBA_mm_P56_P63_4B_CEMBA171213_4B_1_CEMBA171213_4B_2_G8_AD002_indexed.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3771nnn/GSM3771907/suppl/GSM3771907_allc_171219_CEMBA_mm_P56_P63_4B_CEMBA171213_4B_1_CEMBA171213_4B_2_G8_AD004_indexed.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3981nnn/GSM3981399/suppl/GSM3981399_allc_CEMBA181206-5E-3-CEMBA181206-5E-4-E8_ad002.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3981nnn/GSM3981400/suppl/GSM3981400_allc_CEMBA181206-5E-3-CEMBA181206-5E-4-E8_ad004.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3981nnn/GSM3981401/suppl/GSM3981401_allc_CEMBA181206-5E-3-CEMBA181206-5E-4-E8_ad006.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3981nnn/GSM3981403/suppl/GSM3981403_allc_CEMBA181206-5E-3-CEMBA181206-5E-4-E8_ad007.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3981nnn/GSM3981398/suppl/GSM3981398_allc_CEMBA181206-5E-3-CEMBA181206-5E-4-E8_ad008.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3981nnn/GSM3981402/suppl/GSM3981402_allc_CEMBA181206-5E-3-CEMBA181206-5E-4-E8_ad010.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7560nnn/GSM7560624/suppl/GSM7560624_allc_CEMBA200312-6H-1-CEMBA200312-6H-2-G2_ad012.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7560nnn/GSM7560625/suppl/GSM7560625_allc_CEMBA200312-6H-1-CEMBA200312-6H-2-G3_ad001.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7560nnn/GSM7560626/suppl/GSM7560626_allc_CEMBA200312-6H-1-CEMBA200312-6H-2-G3_ad002.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7560nnn/GSM7560627/suppl/GSM7560627_allc_CEMBA200312-6H-1-CEMBA200312-6H-2-G3_ad004.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7560nnn/GSM7560628/suppl/GSM7560628_allc_CEMBA200312-6H-1-CEMBA200312-6H-2-A5_ad008.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7560nnn/GSM7560629/suppl/GSM7560629_allc_CEMBA200312-6H-1-CEMBA200312-6H-2-G3_ad006.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7609nnn/GSM7609207/suppl/GSM7609207_allc_CEMBA200312-8K-1-CEMBA200312-8K-2-C10_ad008.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7611nnn/GSM7611781/suppl/GSM7611781_allc_CEMBA200319-8K-1-CEMBA200319-8K-2-F11_ad006.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7611nnn/GSM7611782/suppl/GSM7611782_allc_CEMBA200319-8K-1-CEMBA200319-8K-2-F11_ad007.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7611nnn/GSM7611783/suppl/GSM7611783_allc_CEMBA200319-8K-1-CEMBA200319-8K-2-F11_ad008.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7611nnn/GSM7611784/suppl/GSM7611784_allc_CEMBA200319-8K-1-CEMBA200319-8K-2-F11_ad010.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7611nnn/GSM7611785/suppl/GSM7611785_allc_CEMBA200319-8K-1-CEMBA200319-8K-2-F11_ad012.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7556nnn/GSM7556506/suppl/GSM7556506_CEMBA200721_6G_3-3-E21-L5.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7556nnn/GSM7556508/suppl/GSM7556508_CEMBA200721_6G_3-3-E21-L6.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7556nnn/GSM7556510/suppl/GSM7556510_CEMBA200721_6G_3-3-E21-M17.allc.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7556nnn/GSM7556512/suppl/GSM7556512_CEMBA200721_6G_3-3-E21-M18.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7556nnn/GSM7556516/suppl/GSM7556516_CEMBA200721_6G_3-3-E21-M6.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7556nnn/GSM7556519/suppl/GSM7556519_CEMBA200721_6G_3-3-E21-N17.allc.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7590nnn/GSM7590208/suppl/GSM7590208_CEMBA201105_7E_1-6-I7-E24.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7590nnn/GSM7590209/suppl/GSM7590209_CEMBA201105_7E_1-6-I7-F11.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7590nnn/GSM7590210/suppl/GSM7590210_CEMBA201105_7E_1-6-I7-F12.allc.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7590nnn/GSM7590211/suppl/GSM7590211_CEMBA201105_7E_1-6-I7-F23.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7590nnn/GSM7590212/suppl/GSM7590212_CEMBA201105_7E_1-6-I7-F24.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7590nnn/GSM7590214/suppl/GSM7590214_CEMBA201105_7E_1-6-I7-G12.allc.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7199nnn/GSM7199742/suppl/GSM7199742_CEMBA210204_11J_3-1-E7-G14.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7199nnn/GSM7199746/suppl/GSM7199746_CEMBA210204_11J_3-1-E7-H1.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7199nnn/GSM7199748/suppl/GSM7199748_CEMBA210204_11J_3-1-E7-H13.allc.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7199nnn/GSM7199750/suppl/GSM7199750_CEMBA210204_11J_3-1-E7-H14.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7199nnn/GSM7199752/suppl/GSM7199752_CEMBA210204_11J_3-1-E7-H2.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7199nnn/GSM7199754/suppl/GSM7199754_CEMBA210204_11J_3-1-E7-I1.allc.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7481nnn/GSM7481907/suppl/GSM7481907_CEMBA210408_15C_2-4-C15-G8.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7481nnn/GSM7481908/suppl/GSM7481908_CEMBA210408_15C_2-4-C15-H19.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7481nnn/GSM7481909/suppl/GSM7481909_CEMBA210408_15C_2-4-C15-H20.allc.tsv.gz'],
       dtype=object),
 array(['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7481nnn/GSM7481910/suppl/GSM7481910_CEMBA210408_15C_2-4-C15-H7.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7481nnn/GSM7481911/suppl/GSM7481911_CEMBA210408_15C_2-4-C15-H8.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7481nnn/GSM7481913/suppl/GSM7481913_CEMBA210408_15C_2-4-C15-I20.allc.tsv.gz',
        ...,
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7523nnn/GSM7523987/suppl/GSM7523987_CEMBA210812_17A_4-1-G10-O2.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7523nnn/GSM7523988/suppl/GSM7523988_CEMBA210812_17A_4-1-G10-P1.allc.tsv.gz',
        'ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM7523nnn/GSM7523989/suppl/GSM7523989_CEMBA210812_17A_4-1-G10-P13.allc.tsv.gz'],
       dtype=object)]

In [25]:
if length % parts != 0:
    parts_list.append(values_download[parts*part_length:])

In [26]:
sumlenglth = 0
for pl in parts_list:
    sumlenglth += len(pl)
if sumlenglth != length:
    print("error")

In [28]:
for i, part in enumerate(parts_list):
    filename = f"/data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_{i+1}.txt"
    with open(filename, 'w') as file:
        for element in part:
            file.write(f"{element}\n")
    print(f"Part {i + 1} written to {filename}")

Part 1 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_1.txt
Part 2 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_2.txt
Part 3 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_3.txt
Part 4 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_4.txt
Part 5 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_5.txt
Part 6 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_6.txt
Part 7 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_7.txt
Part 8 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_8.txt
Part 9 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_9.txt
Part 10 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_10.txt
Part 11 written to /data2st1/junyi/methlyatlas/mCseq/allcfiles_notuse/part_11.txt

In [23]:
tbi_files = glob.glob('/data2st1/junyi/single_allcs/*/*/*.tbi*')

In [24]:
gz_files = glob.glob('/data2st1/junyi/single_allcs/*/*/*.gz')

In [27]:
parseed_tbi = [ f.replace('.tbi',"") for f in tbi_files]

In [28]:
set(gz_files).difference(parseed_tbi)

set()

In [6]:
len(tbi_files)

51536

In [61]:
import os

In [62]:
os.path.basename(tbi_files[0])

'GSM7608355_CEMBA200910_8H_2-6-D15-H23.allc.tsv.gz.tbi'

In [63]:
parseed_gz_based = [ os.path.basename(f) for f in gz_files]

In [64]:
allc_based = [ os.path.basename(f) for f in files]

In [69]:
import shutil

In [70]:
output_folder = '/data2st1/junyi/methlyatlas/mCseq/allcfiles/'

for tbifile in tbi_files:
    dest_name = os.path.basename(tbifile)
    dest_path = os.path.join(output_folder, dest_name)
    if not os.path.exists(dest_path):
        os.link(tbifile, dest_path)
        #print(f"Created symlink for {tbifile} at {dest_path}")
    else:
        print(f"File {dest_path} already exists. Skipping.")

In [71]:
tbis = glob.glob('/data2st1/junyi/methlyatlas/mCseq/allcfiles/*.tbi*')

In [3]:
f_table = glob.glob('/data2st1/junyi/single_allcs/*/*txt')

In [20]:
dest_name

'/data2st1/junyi/merged_allcs/AMY/SCsg_Gabrr2_Gaba.tsv.gz'

In [25]:
import os
outdir= '/data2st1/junyi/merged_allcs/'
f_lists = []
for f in f_table:
    with open(f, 'r') as file:
        lines = file.readlines()
    if len(lines) == 0:
        print(f"File {f} is empty.")
    elif len(lines) == 1:
        fname_base = os.path.basename(f).replace('.txt','')
        region_name = f.split('/')[-2]
        dest_name = os.path.join(outdir, region_name, fname_base + '.tsv.gz')
        # os.symlink(lines[0].strip(), dest_name)
        tbiname=lines[0].strip()+".tbi"
        f_lists.append(f)
        if os.path.exists(tbiname):
            dest_name = os.path.join(outdir, region_name, fname_base + '.tsv.gz.tbi')
            # os.symlink(tbiname, dest_name)
        else:
            print(f"File tbi {tbiname} does not exist.")

File /data2st1/junyi/single_allcs/AMY/nalist.txt is empty.
File /data2st1/junyi/single_allcs/HIP/nalist.txt is empty.

In [32]:
print(len(glob.glob('/data2st1/junyi/single_allcs/HIP/*txt')))
print(len(glob.glob('/data2st1/junyi/single_allcs/PFC/*txt')))
print(len(glob.glob('/data2st1/junyi/single_allcs/AMY/*txt')))

95
39
95

In [10]:
for reion in ['PFC','AMY','HIP']:
    dddset = [ item.split("/")[-1].replace('.txt',"") for item in glob.glob(f'/data2st1/junyi/single_allcs/{reion}/*txt')]
    gzset = [ item.split("/")[-1].replace('.tsv.gz',"") for item in glob.glob(f'/data2st1/junyi/merged_allcs/{reion}/*gz')]
    print(set(dddset).difference(set(gzset)))

{'PFC'}
{'nalist', 'AMY'}
{'HIP', 'nalist'}

In [13]:
HIP_files = glob.glob('/data2st1/junyi/merged_allcs/HIP/*gz')

In [18]:
HIP_Neu = []
for item in HIP_files:
    if not "NN.tsv" in item:
        HIP_Neu.append(item)

In [20]:
with open('/data2st1/junyi/single_allcs/HIP/Neu.txt', 'w') as file:
    for element in HIP_Neu:
        file.write(f"{element}\n")

In [ ]:
print(len(glob.glob('/data2st1/junyi/merged_allcs/HIP/*gz')))
print(len(glob.glob('/data2st1/junyi/merged_allcs/PFC/*gz')))
print(len(glob.glob('/data2st1/junyi/merged_allcs/AMY/*gz')))

97
43
98